version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    install:
      - pip install -U pip
      - pip install . --group doc
      - sudo apt-get install fish
    build:
      html:
        - python -m sphinx -n -j auto -T -b html -d _build/doctrees -D language=$READTHEDOCS_LANGUAGE . $READTHEDOCS_OUTPUT/html
sphinx:
   configuration: docs/source/conf.py
