version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  apt_packages:
    - zsh
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    install:
      - pip install -U pip
      - pip install . --group doc
sphinx:
   configuration: docs/source/conf.py
