version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - zsh
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    install:
      - pip install -U pip
      - pip install . --group doc
      - zsh -lic 'git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"'
      - zsh -lic 'setopt EXTENDED_GLOB; for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do ln -sf "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"; done'
    build:
      html:
        - python -m sphinx -n -j auto -T -b html -d _build/doctrees -D language=$READTHEDOCS_LANGUAGE . $READTHEDOCS_OUTPUT/html
sphinx:
   configuration: docs/source/conf.py
