#! /usr/bin/env python

import logging
import pathlib

import yuio.app
import yuio.config
import yuio.io
import yuio.parse

from typing import Annotated

_logger = logging.getLogger(__name__)


class Config(yuio.config.Config):
    """
    Global options

    Global options are loaded from ``./app_config.json``,
    from environment variables, and from CLI arguments.

    """

    threads: Annotated[int, yuio.parse.Ge(1)] = 4
    """
    Number of threads to use for executing model.

    """

    gpu: bool = True
    """
    Enable or disable gpu.

    """


# We will load values into this variable once the program starts.
CONFIG = Config()


@yuio.app.app(
    version="1.0.0",  # Adds `--version`.
    bug_report=True,  # Adds `--bug-report`.
    is_dev_mode=True,  # Prints warnings from Yuio.
)
def main(
    config: Config = yuio.config.inline(),
):
    """
    Some ml stuff idk im not into ml.

    """

    # Load global config:

    # From file...
    config_file = pathlib.Path(__file__).parent / "app_config.json"
    CONFIG.update(Config.load_from_json_file(config_file))

    # From environment variables...
    CONFIG.update(Config.load_from_env("YUIO"))

    # From CLI arguments...
    CONFIG.update(config)

    _logger.info("Loaded config: %#+r", CONFIG)


main.epilog = """
Formatting
----------

Prolog is formatted using ReStructuredText. Yuio supports all RST formatting except
tables and option lists. It also doesn't have access to all RST directives and roles,
so only a limited subset of them is available.

Example of what we can do:


Quotes
~~~~~~

    | Beautiful python
    | Explicit and simple form
    | Winding through clouds
    |
    | -- from heroku art


Numbered lists
~~~~~~~~~~~~~~

1.  First item,
#.  second item,

a.  or using letters,
#.  continues.


Code blocks
~~~~~~~~~~~

.. code-block:: python

    for i in range(10):
        print(f"Hello, {i}!")


Admonitions
~~~~~~~~~~~

.. note::

    This is an admonition.


Definition and field lists
~~~~~~~~~~~~~~~~~~~~~~~~~~

term
    Definition of the term.

:field: Contents of the field.


Inline markup
~~~~~~~~~~~~~

- **strong**,
- *emphasis*,
- flag role: :flag:`--flag`,
- python roles: :class:`~yuio.app.App`,
- footnotes [#]_ and hyperlinks__.

__ https://example.com
.. [#] This is a footnote.
"""


@main.subcommand(aliases=["r"])
def run(
    #: Trained model to execute.
    model: pathlib.Path = yuio.config.positional(),
    #: Input data for the model.
    data: pathlib.Path = yuio.config.positional(),
):
    """
    Apply trained model to a dataset.

    The model can erase your your storage or drop production database,
    use at your own risk.

    """

    yuio.io.info("Applying model `%s` to data `%s`", model, data)


@main.subcommand(aliases=["t"])
def train(
    #: Input data for the model.
    data: pathlib.Path = yuio.config.positional(),
    #: Output data for the model.
    output: pathlib.Path = yuio.config.field(
        default=pathlib.Path("trained.model"),
        flags=["-o", "--output"],
    ),
):
    """
    Train model on a dataset.

    This will eat all resources on your machine,
    use at your own risk.

    """

    yuio.io.info("Training model `%s` on data `%s`", output, data)


if __name__ == "__main__":
    main.run()
