#! /usr/bin/env python

import os
import sys

import yuio.term

if __name__ == "__main__":
    term = os.environ.get("TERM", "").lower()
    print(f"term = {term}")

    colorterm = os.environ.get("COLORTERM", "").lower()
    print(f"colorterm = {colorterm}")

    has_interactive_output = yuio.term._is_interactive_output(sys.stderr)
    print(f"has_interactive_output = {has_interactive_output}")

    has_interactive_input = yuio.term._is_interactive_input(sys.stdin)
    print(f"has_interactive_input = {has_interactive_input}")

    is_foreground = (
        yuio.term._is_foreground(sys.stderr),
        yuio.term._is_foreground(sys.stdin),
    )
    print(f"is_foreground = {is_foreground}")
    in_ci = yuio.term.detect_ci()
    print(f"in_ci = {in_ci}")

    color_support = yuio.term.detect_ci_color_support()
    print(f"color_support = {color_support.name}")
