Set FontSize 26

Source "docs/source/_tapes/_config.tape"

Sleep 500ms
Type "python examples/widgets/input.py"
Enter
Sleep 2s
Type "Never gonna"
Sleep 250ms
Type " give"
Sleep 250ms
Type " you"
Sleep 250ms
Type "  up..."
Sleep 500ms
Left 5
Sleep 500ms
Backspace
Sleep 500ms
Ctrl+E
Sleep 1s
Ctrl+W
Sleep 250ms
Ctrl+W
Sleep 250ms
Ctrl+W
Sleep 1s
Type "let"
Sleep 250ms
Type " you"
Sleep 250ms
Type " down!"
Sleep 3s
Ctrl+D
Sleep 4s
